repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3 # Replace with latest tag
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
