[tools]
pre-commit = "latest"
node = "lts"
pnpm = "latest"
markdownlint-cli2 = "latest"
prettier = "latest"

[hooks]
enter = "bash ./scripts/setup_project.sh"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
experimental = true
lockfile = true

[tasks.dev]
description = "Dev Mode"
run = "vitepress dev docs --host 0.0.0.0 --port 5555 --cors"
